### ISSUE TITLE
[SUGGESTION]Make support for Zombie Plague gamemode

### ISSUE THREAD

**Issue by Blueberryy** [LeadKiller/leadbot#1]
https://github.com/Nicholas-Fuchs/zombieplague
Bots could play as zombie team

**Comment by Nicholas-Fuchs** [comment]
Leadkiller, I'm the creator of zombie plague. May I have your Steam for a talk?

**Comment by LeadKiller** [comment]
Support is now finished with https://github.com/LeadKiller/leadbot/commit/234cb6a68a4de498aaa8d6cccc7b63a7c9d1da84.
There will still be updates in the future such as more strategies, class loadouts, better hiding, etc.
