### ISSUE TITLE
[SUGGESTION]Darkest Days support

### ISSUE THREAD

**Issue by Blueberryy** [LeadKiller/leadbot#2]
Simple bot that use random loadout of weapons, magic and perks

**Comment by LeadKiller** [comment]
basic bots for darkest days is possible, but they might not be able to perform parkour

**Comment by Blueberryy** [comment]
If you will make them use randomized weapons, skills, magic and perks then that will be enough.

**Comment by LeadKiller** [comment]
darkest days is really fun
